"""
SYMBIONT Sandbox — isolated code execution for agents.

Provides a safe, hermetic execution environment for Worker/Scout agents
that need to run shell commands or manipulate files generated by LLMs.

Design principles (post v0.4.1):
  - Strict path confinement: all file ops are canonicalized and confined
    to declared mounts; path traversal attempts raise PermissionError.
  - Read-only mount enforcement on both file API and shell CWD.
  - cwd pinned to /mnt/workspace so relative paths in commands stay safe.
  - Streaming execution: execute_stream() yields lines in real time so
    agents can observe long-running commands without blocking.
  - DockerSandbox: optional Docker-backed isolation (same Sandbox ABC)
    for untrusted or third-party agent code.
  - Per-thread isolation: one workspace per agent thread, cleaned on release.
  - Async-first: all blocking I/O via asyncio.to_thread.

Usage:
    from symbiont.sandbox import SandboxProvider, SandboxConfig, DockerSandbox

    provider = SandboxProvider(base_dir="~/.symbiont/sandboxes")
    sandbox_id = provider.acquire(thread_id="worker:abc123")

    sb = provider.get(sandbox_id)
    out, code = await sb.execute("ls /mnt/workspace")
    async for line in sb.execute_stream("pip install requests"):
        print(line, end="")
    await sb.write_file("/mnt/workspace/app.py", b"print('hi')")
    content = await sb.read_file("/mnt/workspace/app.py")

    provider.release("worker:abc123")
"""

from __future__ import annotations

import asyncio
import logging
import os
import platform
import shutil
import subprocess
from abc import ABC, abstractmethod
from asyncio import StreamReader
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, AsyncIterator

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Security constants
# ---------------------------------------------------------------------------

_BLOCKED_SYSTEM_PATHS = frozenset({
    "/etc/passwd", "/etc/shadow", "/etc/sudoers",
    "/proc/", "/sys/", "/root/",
})

# ---------------------------------------------------------------------------
# Mount configuration
# ---------------------------------------------------------------------------

@dataclass
class MountConfig:
    """A single filesystem mount visible to sandboxed agents."""
    container_path: str      # Virtual path seen by agents, e.g. /mnt/workspace
    host_path: str           # Real path on the host filesystem
    read_only: bool = False

    def resolve(self) -> Path:
        return Path(self.host_path).expanduser().resolve()


@dataclass
class SandboxConfig:
    """Root configuration for the Sandbox subsystem."""
    base_dir: str = "~/.symbiont/sandboxes"
    extra_mounts: list[MountConfig] = field(default_factory=list)
    bash_output_max_chars: int = 20_000
    read_file_max_chars: int = 50_000
    ls_output_max_chars: int = 20_000
    command_timeout_sec: int = 60
    # DockerSandbox options
    docker_image: str = "python:3.12-slim"
    docker_network: str = "none"          # "none" = no network by default
    block_system_reads: bool = True       # block access to /etc, /proc, /sys, /root


# ---------------------------------------------------------------------------
# Abstract interface
# ---------------------------------------------------------------------------

class Sandbox(ABC):
    """
    Abstract sandbox interface.

    Agents interact only with container-style /mnt/* paths.
    Implementations translate these to real host paths transparently.
    """

    @abstractmethod
    async def execute(self, command: str, timeout: int | None = None) -> tuple[str, int]:
        """Run a shell command. Returns (output, exit_code)."""

    @abstractmethod
    def execute_stream(self, command: str, timeout: int | None = None) -> AsyncIterator[str]:
        """Run a command and yield output lines in real time."""

    @abstractmethod
    async def read_file(self, container_path: str) -> str:
        """Read a file at container_path. Returns content as string."""

    @abstractmethod
    async def write_file(self, container_path: str, content: bytes) -> None:
        """Write bytes to a file at container_path."""

    @abstractmethod
    async def list_dir(self, container_path: str, max_depth: int = 2) -> tuple[list[dict], bool]:
        """List directory. Returns (entries, was_truncated)."""

    @abstractmethod
    async def glob(self, pattern: str) -> tuple[list[str], bool]:
        """Glob pattern within sandbox. Returns (matches, was_truncated)."""

    @abstractmethod
    async def grep(self, pattern: str, paths: list[str]) -> tuple[list[dict], bool]:
        """Grep pattern in paths. Returns (results, was_truncated)."""


# ---------------------------------------------------------------------------
# Local sandbox implementation
# ---------------------------------------------------------------------------

class LocalSandbox(Sandbox):
    """
    Sandbox backed by the local filesystem with strict path confinement.

    Mount table (longest-match wins):
      /mnt/workspace → <base_dir>/<thread_id>/   (writable)
      /mnt/skills    → <skills_dir>/              (read-only)
      + extra mounts from SandboxConfig

    Security guarantees:
      - All Path operations are .resolve()-canonicalized before mount check.
      - Symlinks that escape the mount root are rejected.
      - Shell CWD is pinned to the workspace directory.
      - Host paths are masked in all text output.
    """

    def __init__(
        self,
        sandbox_id: str,
        thread_id: str,
        config: SandboxConfig,
        skills_dir: str | None = None,
    ) -> None:
        self.id = sandbox_id
        self.thread_id = thread_id
        self._config = config

        base = Path(config.base_dir).expanduser().resolve()
        self._workspace = base / _safe_thread_dirname(thread_id)
        self._workspace.mkdir(parents=True, exist_ok=True)

        # mount table: (container_prefix, resolved_host_base, read_only)
        self._mounts: list[tuple[str, Path, bool]] = [
            ("/mnt/workspace", self._workspace, False),
        ]
        if skills_dir:
            skills = Path(skills_dir).expanduser().resolve()
            skills.mkdir(parents=True, exist_ok=True)
            self._mounts.append(("/mnt/skills", skills, True))
        for m in config.extra_mounts:
            host = m.resolve()
            host.mkdir(parents=True, exist_ok=True)
            self._mounts.append((m.container_path, host, m.read_only))

        # longest prefix first for correct match priority
        self._mounts.sort(key=lambda t: len(t[0]), reverse=True)

        logger.debug("sandbox %s: workspace=%s mounts=%d", sandbox_id, self._workspace, len(self._mounts))

    # ------------------------------------------------------------------
    # Path helpers — strict confinement
    # ------------------------------------------------------------------

    def _resolve(self, container_path: str) -> tuple[Path, bool]:
        """
        Translate container path → (real_host_path, is_read_only).

        Raises ValueError  if path is outside all declared mounts.
        Raises PermissionError if resolved path escapes the mount root
                               (symlink or traversal attack).
        """
        for prefix, host_base, read_only in self._mounts:
            if container_path == prefix or container_path.startswith(prefix + "/"):
                relative = container_path[len(prefix):].lstrip("/")
                candidate = (host_base / relative).resolve()
                # Confinement check: resolved path must be inside host_base
                try:
                    candidate.relative_to(host_base)
                except ValueError:
                    raise PermissionError(
                        f"Path traversal detected: '{container_path}' resolves outside mount"
                    )
                return candidate, read_only
        raise ValueError(f"Path '{container_path}' is outside all sandbox mounts")

    def _mask(self, text: str) -> str:
        """Replace host-absolute paths in text with container-style equivalents."""
        for prefix, host_base, _ in self._mounts:
            text = text.replace(str(host_base), prefix)
        return text

    def _inject_mnt(self, command: str) -> str:
        """Substitute /mnt/* references in a shell command with real host paths."""
        for prefix, host_base, _ in self._mounts:
            command = command.replace(prefix, str(host_base))
        return command

    def _check_command_safety(self, command: str) -> None:
        """Raise PermissionError if command references blocked system paths."""
        if not self._config.block_system_reads:
            return
        for blocked in _BLOCKED_SYSTEM_PATHS:
            if blocked in command:
                raise PermissionError(
                    f"Command references blocked system path: {blocked!r}"
                )

    def _detect_shell(self) -> list[str]:
        if platform.system() == "Windows":
            for s in ("powershell.exe", "pwsh.exe", "cmd.exe"):
                if shutil.which(s):
                    return [s]
            return ["cmd.exe"]
        for s in ("/bin/zsh", "/bin/bash", "/bin/sh"):
            if Path(s).exists():
                return [s, "-c"]
        return [shutil.which("sh") or "sh", "-c"]

    # ------------------------------------------------------------------
    # execute — buffered
    # ------------------------------------------------------------------

    async def execute(self, command: str, timeout: int | None = None) -> tuple[str, int]:
        """Run command, buffer all output, return (masked_output, exit_code)."""
        lines: list[str] = []
        code = 0
        async for line in self.execute_stream(command, timeout=timeout):
            lines.append(line)
        # Last item may encode exit code as sentinel "\x00EXIT:<n>"
        if lines and lines[-1].startswith("\x00EXIT:"):
            try:
                code = int(lines[-1][6:])
            except ValueError:
                code = -1
            lines = lines[:-1]
        raw = "".join(lines)
        if len(raw) > self._config.bash_output_max_chars:
            raw = raw[: self._config.bash_output_max_chars] + f"\n[... truncated at {self._config.bash_output_max_chars} chars]"
        return raw, code

    # ------------------------------------------------------------------
    # execute_stream — real-time line iterator (increment #6)
    # ------------------------------------------------------------------

    async def execute_stream(
        self, command: str, timeout: int | None = None
    ) -> AsyncIterator[str]:
        """
        Yield output lines in real time as the command produces them.

        The final yielded item is a sentinel "\x00EXIT:<code>" containing
        the process exit code. Callers that only want buffered output
        should use execute() instead.
        """
        real_cmd = self._inject_mnt(command)
        self._check_command_safety(real_cmd)
        shell = self._detect_shell()
        effective_timeout = timeout or self._config.command_timeout_sec

        proc = await asyncio.create_subprocess_exec(
            *shell, real_cmd,
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.STDOUT,  # merge stderr → stdout
            cwd=str(self._workspace),           # pin CWD to workspace
        )

        async def _read_lines(stream: StreamReader) -> AsyncIterator[str]:
            while True:
                line = await stream.readline()
                if not line:
                    break
                yield self._mask(line.decode(errors="replace"))

        try:
            async with asyncio.timeout(effective_timeout):
                async for line in _read_lines(proc.stdout):
                    yield line
        except TimeoutError:
            proc.kill()
            yield f"[timeout after {effective_timeout}s]\n"
            yield "\x00EXIT:124"
            return
        except Exception as exc:
            proc.kill()
            yield f"[error: {exc}]\n"
            yield "\x00EXIT:-1"
            return

        await proc.wait()
        yield f"\x00EXIT:{proc.returncode}"

    # ------------------------------------------------------------------
    # File operations — confined
    # ------------------------------------------------------------------

    async def read_file(self, container_path: str) -> str:
        host_path, _ = self._resolve(container_path)
        def _read() -> str:
            return host_path.read_text(errors="replace")

        content = await asyncio.to_thread(_read)
        if len(content) > self._config.read_file_max_chars:
            content = content[: self._config.read_file_max_chars] + "\n[... truncated]"
        return content

    async def write_file(self, container_path: str, content: bytes) -> None:
        host_path, read_only = self._resolve(container_path)
        if read_only:
            raise PermissionError(f"Mount containing '{container_path}' is read-only")
        host_path.parent.mkdir(parents=True, exist_ok=True)
        await asyncio.to_thread(host_path.write_bytes, content)

    async def list_dir(self, container_path: str, max_depth: int = 2) -> tuple[list[dict], bool]:
        host_path, _ = self._resolve(container_path)

        def _ls(base: Path, depth: int) -> list[dict]:
            if depth > max_depth:
                return []
            entries: list[dict] = []
            try:
                for item in sorted(base.iterdir()):
                    entries.append({
                        "name": item.name,
                        "path": self._mask(str(item)),
                        "type": "dir" if item.is_dir() else "file",
                        "size": item.stat().st_size if item.is_file() else None,
                    })
                    if item.is_dir():
                        entries.extend(_ls(item, depth + 1))
            except PermissionError:
                pass
            return entries

        all_entries = await asyncio.to_thread(_ls, host_path, 0)
        limit = self._config.ls_output_max_chars // 80
        return all_entries[:limit], len(all_entries) > limit

    async def glob(self, pattern: str) -> tuple[list[str], bool]:
        real_pattern = self._inject_mnt(pattern)
        parts = Path(real_pattern).parts
        base_parts = [p for p in parts if not any(c in p for c in ("*", "?", "["))]
        base = Path(*base_parts) if base_parts else Path(".")

        def _glob() -> list[str]:
            try:
                return [str(p) for p in base.rglob(Path(real_pattern).name)]
            except Exception:
                return []

        matches = await asyncio.to_thread(_glob)
        masked = [self._mask(m) for m in matches]
        return masked[:500], len(masked) > 500

    async def grep(self, pattern: str, paths: list[str]) -> tuple[list[dict], bool]:
        import re
        real_paths = [self._inject_mnt(p) for p in paths]

        def _grep() -> list[dict]:
            try:
                rx = re.compile(pattern)
            except re.error:
                rx = re.compile(re.escape(pattern))
            results: list[dict] = []
            for raw_path in real_paths:
                p = Path(raw_path)
                if not p.is_file():
                    continue
                try:
                    for lineno, line in enumerate(p.read_text(errors="replace").splitlines(), 1):
                        if rx.search(line):
                            results.append({
                                "file": self._mask(str(p)),
                                "line": lineno,
                                "content": line.rstrip(),
                            })
                except Exception:
                    continue
            return results

        results = await asyncio.to_thread(_grep)
        return results[:200], len(results) > 200


# ---------------------------------------------------------------------------
# Docker sandbox — increment #7
# ---------------------------------------------------------------------------

class DockerSandbox(Sandbox):
    """
    Sandbox backed by Docker containers for full OS-level isolation.

    Uses Docker-on-Docker (DooD) pattern: the host Docker socket is NOT
    mounted by default. Each execute() spins up a fresh container, runs
    the command, and removes it (--rm). Workspace files are bind-mounted.

    Prerequisites: Docker daemon accessible to the running process.

    Usage:
        sandbox = DockerSandbox(
            sandbox_id="sb:t1",
            thread_id="t1",
            config=SandboxConfig(docker_image="python:3.12-slim"),
        )
        out, code = await sandbox.execute("python3 /mnt/workspace/app.py")
    """

    def __init__(
        self,
        sandbox_id: str,
        thread_id: str,
        config: SandboxConfig,
        skills_dir: str | None = None,
    ) -> None:
        self.id = sandbox_id
        self.thread_id = thread_id
        self._config = config

        base = Path(config.base_dir).expanduser().resolve()
        self._workspace = base / _safe_thread_dirname(thread_id)
        self._workspace.mkdir(parents=True, exist_ok=True)

        self._skills_dir = Path(skills_dir).expanduser().resolve() if skills_dir else None
        self._image = config.docker_image
        self._network = config.docker_network

    def _docker_run_args(self, command: str) -> list[str]:
        args = [
            "docker", "run", "--rm",
            f"--network={self._network}",
            "--memory=512m",
            "--cpus=1",
            f"-v", f"{self._workspace}:/mnt/workspace",
        ]
        if self._skills_dir and self._skills_dir.exists():
            args += ["-v", f"{self._skills_dir}:/mnt/skills:ro"]
        args += [
            "-w", "/mnt/workspace",
            self._image,
            "sh", "-c", command,
        ]
        return args

    async def execute(self, command: str, timeout: int | None = None) -> tuple[str, int]:
        lines: list[str] = []
        code = 0
        async for line in self.execute_stream(command, timeout=timeout):
            lines.append(line)
        if lines and lines[-1].startswith("\x00EXIT:"):
            try:
                code = int(lines[-1][6:])
            except ValueError:
                code = -1
            lines = lines[:-1]
        raw = "".join(lines)
        if len(raw) > self._config.bash_output_max_chars:
            raw = raw[: self._config.bash_output_max_chars] + "\n[... truncated]"
        return raw, code

    async def execute_stream(
        self, command: str, timeout: int | None = None
    ) -> AsyncIterator[str]:
        args = self._docker_run_args(command)
        effective_timeout = timeout or self._config.command_timeout_sec
        proc = await asyncio.create_subprocess_exec(
            *args,
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.STDOUT,
        )
        try:
            async with asyncio.timeout(effective_timeout):
                async for line in _read_stream(proc.stdout):
                    yield line
        except TimeoutError:
            proc.kill()
            yield f"[docker timeout after {effective_timeout}s]\n"
            yield "\x00EXIT:124"
            return
        await proc.wait()
        yield f"\x00EXIT:{proc.returncode}"

    async def read_file(self, container_path: str) -> str:
        host = self._workspace / container_path.removeprefix("/mnt/workspace/")
        def _read() -> str:
            return host.read_text(errors="replace")
        content = await asyncio.to_thread(_read)
        if len(content) > self._config.read_file_max_chars:
            content = content[: self._config.read_file_max_chars] + "\n[... truncated]"
        return content

    async def write_file(self, container_path: str, content: bytes) -> None:
        host = self._workspace / container_path.removeprefix("/mnt/workspace/")
        host.parent.mkdir(parents=True, exist_ok=True)
        await asyncio.to_thread(host.write_bytes, content)

    async def list_dir(self, container_path: str, max_depth: int = 2) -> tuple[list[dict], bool]:
        out, _ = await self.execute(f"find /mnt/workspace -maxdepth {max_depth} -print")
        entries = [{"path": line.strip(), "type": "unknown"} for line in out.splitlines() if line.strip()]
        return entries[:250], len(entries) > 250

    async def glob(self, pattern: str) -> tuple[list[str], bool]:
        out, _ = await self.execute(f"find /mnt/workspace -name '{Path(pattern).name}'")
        matches = [l.strip() for l in out.splitlines() if l.strip()]
        return matches[:500], len(matches) > 500

    async def grep(self, pattern: str, paths: list[str]) -> tuple[list[dict], bool]:
        paths_str = " ".join(f'"{p}"' for p in paths)
        out, _ = await self.execute(f"grep -rn '{pattern}' {paths_str} 2>/dev/null")
        results = []
        for line in out.splitlines():
            parts = line.split(":", 2)
            if len(parts) >= 3:
                try:
                    results.append({"file": parts[0], "line": int(parts[1]), "content": parts[2]})
                except ValueError:
                    continue
        return results[:200], len(results) > 200


# ---------------------------------------------------------------------------
# Provider
# ---------------------------------------------------------------------------

class SandboxProvider:
    """
    Factory and lifecycle manager for Sandbox instances.

    backend="local"  → LocalSandbox  (default)
    backend="docker" → DockerSandbox (requires Docker daemon)
    """

    def __init__(
        self,
        config: SandboxConfig | None = None,
        skills_dir: str | None = None,
        backend: str = "local",
    ) -> None:
        self._config = config or SandboxConfig()
        self._skills_dir = skills_dir
        self._backend = backend
        self._sandboxes: dict[str, Sandbox] = {}

    def acquire(self, thread_id: str) -> str:
        """Return sandbox_id for thread_id, creating if needed."""
        if thread_id not in self._sandboxes:
            sandbox_id = f"sb:{thread_id}"
            if self._backend == "docker":
                sb: Sandbox = DockerSandbox(
                    sandbox_id=sandbox_id, thread_id=thread_id,
                    config=self._config, skills_dir=self._skills_dir,
                )
            else:
                sb = LocalSandbox(
                    sandbox_id=sandbox_id, thread_id=thread_id,
                    config=self._config, skills_dir=self._skills_dir,
                )
            self._sandboxes[thread_id] = sb
            logger.info("sandbox: acquired %s [%s] for thread %s", sandbox_id, self._backend, thread_id)
        return self._sandboxes[thread_id].id

    def get(self, sandbox_id: str) -> Sandbox | None:
        for sb in self._sandboxes.values():
            if sb.id == sandbox_id:
                return sb
        return None

    def get_by_thread(self, thread_id: str) -> Sandbox | None:
        return self._sandboxes.get(thread_id)

    def release(self, thread_id: str) -> None:
        sb = self._sandboxes.pop(thread_id, None)
        if sb:
            workspace = Path(self._config.base_dir).expanduser() / _safe_thread_dirname(thread_id)
            try:
                shutil.rmtree(workspace, ignore_errors=True)
                logger.info("sandbox: released %s, workspace cleaned", sb.id)
            except Exception as exc:
                logger.warning("sandbox: cleanup failed for %s: %s", sb.id, exc)

    def shutdown(self) -> None:
        for tid in list(self._sandboxes):
            self.release(tid)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _safe_thread_dirname(thread_id: str) -> str:
    """Sanitize thread_id for use as a directory name."""
    return thread_id.replace("/", "_").replace(":", "_").replace("..", "_")


async def _read_stream(stream: StreamReader) -> AsyncIterator[str]:
    while True:
        line = await stream.readline()
        if not line:
            break
        yield line.decode(errors="replace")


# ---------------------------------------------------------------------------
# Module-level singleton
# ---------------------------------------------------------------------------

_provider: SandboxProvider | None = None


def get_sandbox_provider(
    config: SandboxConfig | None = None,
    skills_dir: str | None = None,
    backend: str = "local",
) -> SandboxProvider:
    global _provider
    if _provider is None:
        _provider = SandboxProvider(config=config, skills_dir=skills_dir, backend=backend)
    return _provider
