"""
SYMBIONT Tools — CLI Anything integration for GUI app automation.

Enables SYMBIONT agents (Workers, Scouts) to operate GUI software
via CLI harnesses generated by the cli-anything plugin.

Supported apps (if harness exists):
- GIMP (image editing)
- LibreOffice (documents)
- Blender (3D)
- Inkscape (vector graphics)
- Audacity (audio)
- OBS Studio (recording/streaming)

Usage:
    from symbiont.tools import ToolRegistry

    tools = ToolRegistry()
    tools.list_available()  # Show installed harnesses

    # Execute a tool command
    result = await tools.run("gimp", "open image.png && apply-filter sharpen")

    # In a Worker agent context:
    worker.tools = ToolRegistry()
    result = await worker.use_tool("gimp", "resize 800x600 output.png")
"""

from __future__ import annotations

import asyncio
import logging
import shutil
import subprocess
from pathlib import Path
from typing import Any

logger = logging.getLogger(__name__)

# Known CLI Anything harnesses and their expected binary names
KNOWN_HARNESSES = {
    "gimp": {"binary": "gimp-cli", "package": "gimp-cli-harness", "category": "image"},
    "libreoffice": {"binary": "lo-cli", "package": "libreoffice-cli-harness", "category": "document"},
    "blender": {"binary": "blender-cli", "package": "blender-cli-harness", "category": "3d"},
    "inkscape": {"binary": "inkscape-cli", "package": "inkscape-cli-harness", "category": "vector"},
    "audacity": {"binary": "audacity-cli", "package": "audacity-cli-harness", "category": "audio"},
    "obs": {"binary": "obs-cli", "package": "obs-cli-harness", "category": "recording"},
    "kdenlive": {"binary": "kdenlive-cli", "package": "kdenlive-cli-harness", "category": "video"},
}


class ToolRegistry:
    """Registry of available CLI harnesses for SYMBIONT agents."""

    def __init__(self) -> None:
        self._available: dict[str, dict] = {}
        self._detect_harnesses()
        self._detect_system_tools()

    def _detect_harnesses(self) -> None:
        """Detect installed CLI Anything harnesses."""
        for name, info in KNOWN_HARNESSES.items():
            binary = shutil.which(info["binary"])
            if binary:
                self._available[name] = {
                    **info,
                    "path": binary,
                    "type": "harness",
                }
                logger.info("tools: found harness '%s' at %s", name, binary)

    def _detect_system_tools(self) -> None:
        """Detect useful system CLI tools that agents can use directly."""
        system_tools = {
            "ffmpeg": {"binary": "ffmpeg", "category": "media", "desc": "Audio/video processing"},
            "imagemagick": {"binary": "convert", "category": "image", "desc": "Image manipulation"},
            "pandoc": {"binary": "pandoc", "category": "document", "desc": "Document conversion"},
            "sox": {"binary": "sox", "category": "audio", "desc": "Audio processing"},
            "yt-dlp": {"binary": "yt-dlp", "category": "media", "desc": "Video download"},
            "jq": {"binary": "jq", "category": "data", "desc": "JSON processing"},
            "sqlite3": {"binary": "sqlite3", "category": "data", "desc": "Database queries"},
            "curl": {"binary": "curl", "category": "network", "desc": "HTTP requests"},
            "git": {"binary": "git", "category": "dev", "desc": "Version control"},
        }

        for name, info in system_tools.items():
            binary = shutil.which(info["binary"])
            if binary:
                self._available[name] = {
                    **info,
                    "path": binary,
                    "type": "system",
                }

    @property
    def available_tools(self) -> dict[str, dict]:
        return self._available

    def list_available(self) -> list[dict]:
        """List all available tools with their details."""
        return [
            {"name": name, **info}
            for name, info in sorted(self._available.items())
        ]

    def has_tool(self, name: str) -> bool:
        return name in self._available

    def get_tool_path(self, name: str) -> str | None:
        tool = self._available.get(name)
        return tool["path"] if tool else None

    async def run(self, tool_name: str, command: str, timeout: int = 60) -> dict:
        """
        Execute a tool command.

        Args:
            tool_name: Name of the tool (e.g., "gimp", "ffmpeg")
            command: Command to execute (arguments after the binary name)
            timeout: Max execution time in seconds

        Returns:
            dict with stdout, stderr, returncode
        """
        if not self.has_tool(tool_name):
            return {"error": f"Tool '{tool_name}' not available", "returncode": -1}

        tool_path = self.get_tool_path(tool_name)
        full_command = f"{tool_path} {command}"

        try:
            result = await asyncio.to_thread(
                subprocess.run,
                full_command,
                shell=True,
                capture_output=True,
                text=True,
                timeout=timeout,
            )
            return {
                "stdout": result.stdout,
                "stderr": result.stderr,
                "returncode": result.returncode,
            }
        except subprocess.TimeoutExpired:
            return {"error": f"Timeout after {timeout}s", "returncode": -2}
        except Exception as e:
            return {"error": str(e), "returncode": -3}

    def by_category(self, category: str) -> list[str]:
        """Get tools by category (image, audio, document, etc)."""
        return [
            name for name, info in self._available.items()
            if info.get("category") == category
        ]

    def summary(self) -> dict:
        """Summary for display."""
        harnesses = [n for n, i in self._available.items() if i["type"] == "harness"]
        system = [n for n, i in self._available.items() if i["type"] == "system"]
        return {
            "harnesses": harnesses,
            "system_tools": system,
            "total": len(self._available),
        }
